replicaCount: 2

image:
  repository: heart-disease-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
  className: nginx
  host: heart-api.local

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 15
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
